server:
  port: 10010
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5
zuul:
  prefix: /api #路由路径前缀
  routes:
    item-service: /item/** #路由到商品微服务
    search-service: /search/** #路由到搜索微服务
    user-service: /user/** #用户微服务
    auth-service: /auth/** #授权中心微服务
    cart-service: /cart/**
  add-host-header: true
  sensitive-headers:
leyou:
  jwt:
    pubKeyPath: D:\\leyou\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item